# Generated by Django 4.0.5 on 2022-07-04 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 14, 46, 47, 256938, tzinfo=utc), verbose_name='게시 일자'),
        ),
    ]
