# Generated by Django 4.0.5 on 2022-06-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='output',
            field=models.ImageField(default='', upload_to='article/media/', verbose_name='결과물'),
        ),
        migrations.AlterField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(auto_now_add=True, verbose_name='게시 일자'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='article/media/', verbose_name='이미지'),
        ),
    ]
