# Generated by Django 4.0.5 on 2022-06-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_output_alter_article_exposure_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article/media/', verbose_name='이미지'),
        ),
    ]
