# Generated by Django 4.0.5 on 2022-07-04 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_exposure_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 17, 16, 43, 621672, tzinfo=utc), verbose_name='게시 일자'),
        ),
    ]
