# Generated by Django 4.0.5 on 2022-06-29 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='output',
        ),
        migrations.AlterField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 29, 12, 39, 22, 91338, tzinfo=utc), verbose_name='게시 일자'),
        ),
    ]
