# Generated by Django 4.0.5 on 2022-07-05 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_exposure_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 5, 7, 35, 54, 136164, tzinfo=utc), verbose_name='게시 일자'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_converted',
            field=models.FileField(null=True, upload_to='paint/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='output',
            field=models.ImageField(default='', upload_to='output/', verbose_name='결과물'),
        ),
    ]
