# Generated by Django 4.0.5 on 2022-06-29 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_exposure_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='output',
            field=models.ImageField(default='', upload_to='article/media/', verbose_name='결과물'),
        ),
        migrations.AlterField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 29, 12, 58, 12, 876360, tzinfo=utc), verbose_name='게시 일자'),
        ),
    ]
