# Generated by Django 4.0.5 on 2022-07-02 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_article_exposure_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 14, 31, 56, 743951, tzinfo=utc), verbose_name='게시 일자'),
        ),
    ]
